#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * use the machine name character to detect current environment
 * current dev environment is linux scotchbox 3.13.0-55-generic #94-Ubuntu SMP
 * current prod environment is Linux blog 3.13.0-43-generic #72-Ubuntu SMP
 * So here we can detect environment based on that
 */
if( strpos(php_uname(), 'scotchbox') !== false ) {
	define('YII_DEBUG', true);
	define('YII_ENV', 'dev');	
}else {
	define('YII_DEBUG', false);
	define('YII_ENV', 'prod');
}

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
